version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: tc_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: library/php
    container_name: tc_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  clickhouse:
    container_name: tc_clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  tc_clickhouse:
